POST localhost:8080/v1/db/open
Content-Type: application/json

{
  "name": "piet",
  "password": "piet1"
}

###

POST localhost:8080/v1/objects
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "stoel",
  "quantity": 1
}


###

GET localhost:8080/v1/objects
Authorization: Bearer <token>