POST localhost:8080/v1/db/open
Content-Type: application/json

{
  "name": "test",
  "password": "test123"
}

###

POST localhost:8080/v1/objects
Content-Type: application/json
Authorization: Bearer DLZXNYO5D3P3BXQQPP76IDNPXI

{
  "name": "stoel",
  "quantity": 1
}


###

GET localhost:8080/v1/objects
Authorization: Bearer DLZXNYO5D3P3BXQQPP76IDNPXI