POST localhost:8080/v1/db/open
Content-Type: application/json

{
  "name": "test",
  "password": "test123"
}

###

POST localhost:8080/v1/objects
Content-Type: application/json
Authorization: Bearer RJUFIK2N4F4EQHCS4TJ4KDWZEA

{
  "name": "tafel",
  "quantity": 1
}


###

GET localhost:8080/v1/objects
Authorization: Bearer RJUFIK2N4F4EQHCS4TJ4KDWZEA